/*
SQLyog Community v11.27 (32 bit)
MySQL - 5.5.35 : Database - tweed
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Table structure for table `tweets` */

DROP TABLE IF EXISTS `tweets`;

CREATE TABLE `tweets` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `campaign_id` bigint(20) unsigned NOT NULL,
  `iso_lang` varchar(5) NOT NULL,
  `user_id` varchar(20) NOT NULL,
  `user_name` varchar(100) NOT NULL,
  `user_screen_name` varchar(100) NOT NULL,
  `user_location` varchar(100) NOT NULL,
  `tweet_id` varchar(20) NOT NULL,
  `created_at` datetime NOT NULL,
  `content` varchar(250) NOT NULL,
  `source` varchar(150) NOT NULL,
  `in_reply_to_id` varchar(20) DEFAULT NULL,
  `in_reply_to_screen_name` varchar(100) DEFAULT NULL,
  `retweet_count` int(10) unsigned NOT NULL DEFAULT '0',
  `approved` enum('yes','no') NOT NULL DEFAULT 'no',
  PRIMARY KEY (`id`),
  UNIQUE KEY `tweet_id` (`tweet_id`,`campaign_id`)
) ENGINE=InnoDB AUTO_INCREMENT=234 DEFAULT CHARSET=utf8;

/*Data for the table `tweets` */

insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (134,1,'en','2980473756','SchooLinks','SchooLinks_News','','637182254394015744','2015-08-28 09:37:42','@taagbo Help us solve the issues of the Education Gap. Vote for us, it takes 30 seconds #SXSW http://t.co/sWXouzqpxc','<a href=\"http://wikihikma.com\" rel=\"nofollow\">Wikihikma</a>','241438862','taagbo',0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (135,1,'en','405654817','Rhiza Nery','rhizaweeza','Manila, Philippines','637181416401342465','2015-08-28 09:34:22','Help civic tech learn to do #WithNotFor public engagement at #SXSW http://t.co/aFDT9YYRNC #civictech #opengov #panelpicker','<a href=\"http://twitter.com/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>',NULL,NULL,1,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (136,1,'en','158145014','NewCitiesFoundation','newcitiesfound','Paris, France','637180821741285380','2015-08-28 09:32:00','Tech will transform how cities &amp; citizens think about space - @placemeter &amp; John @Rossant &gt; #SXSW panel submission http://t.co/VxkhRytHjZ','<a href=\"http://sproutsocial.com\" rel=\"nofollow\">Sprout Social</a>',NULL,NULL,0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (137,1,'en','2980473756','SchooLinks','SchooLinks_News','','637179953478565889','2015-08-28 09:28:33','@KroviaTV By voting for us, you\'ll help millions of underprivileged students succeed. #SXSW  http://t.co/jYfzPSXUOJ','<a href=\"http://wikihikma.com\" rel=\"nofollow\">Wikihikma</a>','3240815123','KroviaTV',0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (138,1,'en','208584178','Rana el Kaliouby','kaliouby','Boston','637177262417297413','2015-08-28 09:17:52','We\'d like to bring a session on emotion sensing and digital experiences to #SXSW - vote for us on PanelPicker: https://t.co/uMmKH2nQ5E','<a href=\"http://twitter.com/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>',NULL,NULL,1,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (139,1,'en','3436392257','ArticleWriterr','ArticleWriterr','Magyarország','637176096199450624','2015-08-28 09:13:14','The Fourth “Dimension” of #SXSW  http://t.co/tCv1RpuAXn RT @AustinFoodTour','<a href=\"http://viralcontentbuzz.com\" rel=\"nofollow\">Viral Content Buzz</a>',NULL,NULL,0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (140,1,'en','55185470','Alex Gaspar','banzounet','Belgium','637173859431620608','2015-08-28 09:04:20','Don\'t forget to cast your vote and help send us to #SXSW! http://t.co/yRuPOVOqvL http://t.co/4cxSETfkUh','<a href=\"http://twitter.com\" rel=\"nofollow\">Twitter Web Client</a>',NULL,NULL,2,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (141,1,'en','2980473756','SchooLinks','SchooLinks_News','','637171499640717312','2015-08-28 08:54:58','@StraitMusicCo After you vote us into #SXSW, @entrepreneur will want to feature us, Front Page!  http://t.co/jYfzPSXUOJ','<a href=\"http://wikihikma.com\" rel=\"nofollow\">Wikihikma</a>','358013410','StraitMusicCo',0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (142,1,'en','3192600423','Poproxx','poproxx1','Tennessee, USA','637169306548178945','2015-08-28 08:46:15','Dej Loaf Made Her Presence Known at SXSW\n\nhttp://t.co/GtaOREx0Se\n\n#dejloaf #sxsw http://t.co/4gnhGHwIje','<a href=\"https://www.socialoomph.com\" rel=\"nofollow\">SocialOomph</a>',NULL,NULL,0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (143,1,'en','2980473756','SchooLinks','SchooLinks_News','','637165867713888256','2015-08-28 08:32:35','@EMC_Fresno Be a part of the bigger picture today, by voting for into #SXSW  http://t.co/sWXouzqpxc','<a href=\"http://wikihikma.com\" rel=\"nofollow\">Wikihikma</a>','3024503971','EMC_Fresno',0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (144,1,'en','14190399','Metaphysicalist','Metaphysicalist','London','637161201315647488','2015-08-28 08:14:02','Stower Selected as Finalist for the SXSW Eco Startup Showcase Competition: San Francisco, CA, August 28,... http://t.co/zGAXjIJX9S #SXSW','<a href=\"http://twitterfeed.com\" rel=\"nofollow\">twitterfeed</a>',NULL,NULL,0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (145,1,'en','2980473756','SchooLinks','SchooLinks_News','','637159496910024704','2015-08-28 08:07:16','@Lisa_Haffelder Want to know something cool? We\'re headed to #SXSW, but we need 1 last vote: yours! http://t.co/jYfzPSXUOJ','<a href=\"http://wikihikma.com\" rel=\"nofollow\">Wikihikma</a>','3338845933','Lisa_Haffelder',0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (146,1,'en','18986537','Ian M Calvert','IanMCalvert','Oxfordshire, England','637158991861125120','2015-08-28 08:05:16','Help get @bryankramer to #SXSW by voting for #Shareology: How Sharing Powers the Human Economy http://t.co/YSvoXAJO7V','<a href=\"http://www.influitive.com\" rel=\"nofollow\">Influitive</a>',NULL,NULL,0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (147,1,'en','2980473756','SchooLinks','SchooLinks_News','','637158516860522496','2015-08-28 08:03:22','@CL1nk We can be the biggest thing in EdTech since...well, vote for us and find out ; ) #SXSW http://t.co/i0zv29omxZ','<a href=\"http://wikihikma.com\" rel=\"nofollow\">Wikihikma</a>','15329769','CL1nk',0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (148,1,'en','16493868','Bryan Kramer','bryankramer','San Jose, CA','637157930081644544','2015-08-28 08:01:03','Friends, I would love your help in getting to speak at #SXSW http://t.co/d1IpzBLAYj  #shareology #H2H #H2HChat #thankyou','<a href=\"http://www.tweetjukebox.com\" rel=\"nofollow\">Tweet Jukebox</a>',NULL,NULL,0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (149,1,'en','2980473756','SchooLinks','SchooLinks_News','','637156526122225664','2015-08-28 07:55:28','@dh8hwlkwkg Inner City students need our help and we need your help, please vote us into this year\'s #SXSW http://t.co/i0zv29omxZ','<a href=\"http://wikihikma.com\" rel=\"nofollow\">Wikihikma</a>','3339408924','dh8hwlkwkg',0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (150,1,'en','3090138010','Dull - trending!!','Swipe_SXSW_Left','Austin, TX','637154656846807040','2015-08-28 07:48:02','Want to know why the snob effect is a serious problem for digital designers? Vote Me(rel) to #SXSW 16! #UX #UXD #SXSW http://t.co/HvfWbMBd6B','<a href=\"http://shoudio.com\" rel=\"nofollow\">Shoudio</a>',NULL,NULL,1,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (151,1,'en','2701408981','JILOU mohamed','JILOUmohamed','California, USA','637154447978659841','2015-08-28 07:47:12','Want to see an awesome session at #SxSW about #socialdata? Vote for @nik today! http://t.co/ui7UTNZgS0','<a href=\"http://twitter.com\" rel=\"nofollow\">Twitter Web Client</a>',NULL,NULL,1,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (152,1,'en','2980473756','SchooLinks','SchooLinks_News','','637154306618212352','2015-08-28 07:46:39','@lowestpricesonl Be a part of the EdTech Discussions, vote for our #SXSW Panel #EdTech http://t.co/sWXouzqpxc','<a href=\"http://wikihikma.com\" rel=\"nofollow\">Wikihikma</a>','3339434112','lowestpricesonl',0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (153,1,'en','214239236','Merel Backers','Merelbackers','Amsterdam, The Netherlands','637153433737297920','2015-08-28 07:43:10','Want to know why the snob effect is a serious problem for digital designers? Vote Me(rel) to #SXSW 16! #UX #UXD #SXSW http://t.co/HvfWbMBd6B','<a href=\"http://twitter.com/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>',NULL,NULL,1,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (154,1,'en','2980473756','SchooLinks','SchooLinks_News','','637152739496230912','2015-08-28 07:40:25','@SBRPGB #SXSW is coming up quick! Vote for Schoolinks : ) #SXSWedu http://t.co/jYfzPSXUOJ','<a href=\"http://wikihikma.com\" rel=\"nofollow\">Wikihikma</a>','3339513680','SBRPGB',0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (155,1,'en','2980473756','SchooLinks','SchooLinks_News','','637151415446708225','2015-08-28 07:35:09','@eric41845046 Quick! Time is running out, vote for us now! #SXSW http://t.co/sWXouzqpxc','<a href=\"http://wikihikma.com\" rel=\"nofollow\">Wikihikma</a>','3439391051','eric41845046',0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (156,1,'en','40808900','p u N K t  aSaMaKi','cw4t7abs','Earth Sol 1 MilkyWay Laniakea ','637150206178521088','2015-08-28 07:30:21','Is this the next level of human augmentation? Vote for @roseveleth to talk at #sxsw here: http://t.co/DIyAfPBpk1 http://t.co/jROIfSXbCP','<a href=\"http://twitter.com\" rel=\"nofollow\">Twitter Web Client</a>',NULL,NULL,3,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (157,1,'en','2980473756','SchooLinks','SchooLinks_News','','637149156218380288','2015-08-28 07:26:11','@MindBridgeP Quick! Time is running out, vote for us now! #SXSW http://t.co/sWXouzqpxc','<a href=\"http://wikihikma.com\" rel=\"nofollow\">Wikihikma</a>','3279034670','MindBridgeP',0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (158,1,'en','1374581','Julia Ervin','JungleJulia','i\'m all over the place','637149094973206528','2015-08-28 07:25:56','Later...like, March? #SXSW #callme https://t.co/mqdVpfLVEj','<a href=\"http://twitter.com\" rel=\"nofollow\">Twitter Web Client</a>',NULL,NULL,0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (159,1,'en','3192600423','Poproxx','poproxx1','Tennessee, USA','637148650095964160','2015-08-28 07:24:10','SXSW 2015 Recap\n\nhttp://t.co/FQGx1wSCWk\n\n#sxsw #recap #2015 http://t.co/VpTclE0OYb','<a href=\"https://www.socialoomph.com\" rel=\"nofollow\">SocialOomph</a>',NULL,NULL,0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (160,1,'en','20775453','Simon Goodall','SiGoodall','','637144944549986304','2015-08-28 07:09:27','Vote shopping on Apple watch by @Justyna_Po and more brilliant #SXSW #Panelpicker entries! http://t.co/C0giKM71lA http://t.co/hfDYV6iYkn','<a href=\"http://twitter.com/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>',NULL,NULL,1,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (161,1,'en','2980473756','SchooLinks','SchooLinks_News','','637144589653164032','2015-08-28 07:08:02','@GappedToothGirl Quick! Time is running out, vote for us now! #SXSW http://t.co/sWXouzqpxc','<a href=\"http://wikihikma.com\" rel=\"nofollow\">Wikihikma</a>','3127524716','GappedToothGirl',0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (162,1,'en','3061133886','SXSW Top Stories','SXSW_ca','','637142826334052354','2015-08-28 07:01:01','Inside the PanelPicker: Delivery-On-Demand Economy Grows http://t.co/OnrZL6dko6 via @adplat #SXSW','<a href=\"https://about.twitter.com/products/tweetdeck\" rel=\"nofollow\">TweetDeck</a>',NULL,NULL,0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (163,1,'en','16493868','Bryan Kramer','bryankramer','San Jose, CA','637142707450871808','2015-08-28 07:00:33','Please vote for me to speak at #SXSW for #Shareology: How Sharing Powers the Human Economy http://t.co/NYY3PAs0Si http://t.co/Zw059AsZBu','<a href=\"http://www.tweetjukebox.com\" rel=\"nofollow\">Tweet Jukebox</a>',NULL,NULL,0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (164,1,'en','2980473756','SchooLinks','SchooLinks_News','','637142307393957888','2015-08-28 06:58:58','@jamieandnic Help our #EdTech Startup get into #SXSW by voting for us : )  http://t.co/i0zv29omxZ','<a href=\"http://wikihikma.com\" rel=\"nofollow\">Wikihikma</a>','3439466932','jamieandnic',0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (165,1,'en','42126609','Chuckie Campbell','ChuckieC2','Buffalo, NY','637141756056838144','2015-08-28 06:56:46','Video: CANALSIDE, stay tuned! Much love to @dennykremblascreative #buffalo #music #canalside #sxsw #nxne... http://t.co/chYlsd2d56','<a href=\"http://www.tumblr.com/\" rel=\"nofollow\">Tumblr</a>',NULL,NULL,0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (166,1,'en','42126609','Chuckie Campbell','ChuckieC2','Buffalo, NY','637141753540288512','2015-08-28 06:56:46','CANALSIDE, stay tuned! Much love to dennykremblascreative #buffalo #music #canalside #sxsw #nxne… https://t.co/ZrZVXiaocs','<a href=\"http://instagram.com\" rel=\"nofollow\">Instagram</a>',NULL,NULL,0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (167,1,'en','2980473756','SchooLinks','SchooLinks_News','','637138493710422016','2015-08-28 06:43:49','@EastsideJonesDH We would love your help, please vote for us : ) #SXSW #PanelPicker http://t.co/jYfzPSXUOJ','<a href=\"http://wikihikma.com\" rel=\"nofollow\">Wikihikma</a>','1228798422','EastsideJonesDH',0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (168,1,'en','2763405666','Ralph Ehlers','TheRalphEhlers','United Kingdom','637138052339662848','2015-08-28 06:42:03','Tinder Users at #SXSW Fell for This Woman, but She\'s Not What She Appears: http://t.co/QOTABXNYL7 http://t.co/5vM9p5Qc2W','<a href=\"https://roundteam.co\" rel=\"nofollow\">RoundTeam</a>',NULL,NULL,1,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (169,1,'en','35611404','Tammy Han','TammyFabulous','San Francisco, CA','637137546527412224','2015-08-28 06:40:03','What #data will parents need in the future? Vote to hear @chrisabruce @RosalindPicard @davidrose sound off #sxsw http://t.co/k39Hg3Y61b','<a href=\"http://twitter.com/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>',NULL,NULL,1,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (170,1,'en','14190399','Metaphysicalist','Metaphysicalist','London','637137251315527680','2015-08-28 06:38:52','From a local dive to the big screen, the Jones Family have made their own way: The team scored a debut a... http://t.co/RUM1Z0oNEA #SXSW','<a href=\"http://twitterfeed.com\" rel=\"nofollow\">twitterfeed</a>',NULL,NULL,0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (171,1,'en','14190399','Metaphysicalist','Metaphysicalist','London','637137250237550593','2015-08-28 06:38:52','Watch The Trailer For Colin Hanks’ Tower Records Documentary: The late, great Tower Records is now the s... http://t.co/eBymN7y3Gd #SXSW','<a href=\"http://twitterfeed.com\" rel=\"nofollow\">twitterfeed</a>',NULL,NULL,0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (172,1,'en','524662686','Franken Harpo','FrankenHarpo','','637136880337833985','2015-08-28 06:37:24','Is this the next level of human augmentation? Vote for @roseveleth to talk at #sxsw here: http://t.co/DIyAfPBpk1 http://t.co/jROIfSXbCP','<a href=\"http://twitter.com/#!/download/ipad\" rel=\"nofollow\">Twitter for iPad</a>',NULL,NULL,3,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (173,1,'en','14747961','Pramit Nairi','pramitnairi','Los Angeles, CA','637136814092845057','2015-08-28 06:37:08','If u feel email is productivity\'s kryptonite, pls help me get this panel on SXSW. http://t.co/pTHqodzoeq #SXSW cc @timleake #HIMC','<a href=\"http://tapbots.com/software/tweetbot/mac\" rel=\"nofollow\">Tweetbot for Mac</a>',NULL,NULL,1,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (174,1,'en','121336088','Qualaroo ','QualarooInc','San Mateo, CA','637136554260099072','2015-08-28 06:36:06','Tinder Users at #SXSW Fell for This Woman, but She\'s Not What She Appears: http://t.co/QOTABXNYL7 http://t.co/5vM9p5Qc2W','<a href=\"http://bufferapp.com\" rel=\"nofollow\">Buffer</a>',NULL,NULL,1,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (175,1,'en','138334172','Dmitry Timofeev','timdim75','','637136524807696384','2015-08-28 06:35:59','Is this the next level of human augmentation? Vote for @roseveleth to talk at #sxsw here: http://t.co/DIyAfPBpk1 http://t.co/jROIfSXbCP','<a href=\"http://twitter.com/download/android\" rel=\"nofollow\">Twitter for Android</a>',NULL,NULL,3,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (176,1,'en','2980473756','SchooLinks','SchooLinks_News','','637135441116925952','2015-08-28 06:31:41','@Artutechent Passtionate about #EdTech? We are too! Vote us into #SXSW http://t.co/sWXouzqpxc','<a href=\"http://wikihikma.com\" rel=\"nofollow\">Wikihikma</a>','2960847207','Artutechent',0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (177,1,'en','410605574','BBC Future','BBC_Future','','637135247709237248','2015-08-28 06:30:55','Is this the next level of human augmentation? Vote for @roseveleth to talk at #sxsw here: http://t.co/DIyAfPBpk1 http://t.co/jROIfSXbCP','<a href=\"http://www.hootsuite.com\" rel=\"nofollow\">Hootsuite</a>',NULL,NULL,3,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (178,1,'en','2354765722','anamarisculturetas','anamarisculture','','637133822212050944','2015-08-28 06:25:15','Our weekly #tbt countdown to #SXSW30 continues with this rad poster from #SXSW 1990. Design by Nels Jacobson. http://t.co/Rt4G5qj79V','<a href=\"http://www.flipboard.com\" rel=\"nofollow\">Flipboard</a>',NULL,NULL,13,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (179,1,'en','2980473756','SchooLinks','SchooLinks_News','','637132688881811456','2015-08-28 06:20:45','@Brian_S_LADC Want to make education accessible to everyone? We need your help. Please vote for us! #SXSW http://t.co/jYfzPSXUOJ','<a href=\"http://wikihikma.com\" rel=\"nofollow\">Wikihikma</a>','370510365','Brian_S_LADC',0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (180,1,'en','3156301850','Indian Startups','indianstartups1','','637131341658624001','2015-08-28 06:15:23','Hear how human-centered #design will be the ultimate #startup secret weapon. Vote for our #SXSW panel today: http://t.co/wP233MKNQy','<a href=\"http://twitter.com\" rel=\"nofollow\">Twitter Web Client</a>',NULL,NULL,1,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (181,1,'en','2980473756','SchooLinks','SchooLinks_News','','637128768038039552','2015-08-28 06:05:10','@harley_maye Interested in the discussion of Higher Education? Vote to join our Discussion! #SXSW http://t.co/jYfzPSXUOJ','<a href=\"http://wikihikma.com\" rel=\"nofollow\">Wikihikma</a>','3339846192','harley_maye',0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (182,1,'en','782586474','Sproutling','sproutling','San Francisco, CA','637128475652964353','2015-08-28 06:04:00','What #data will parents need in the future? Vote to hear @chrisabruce @RosalindPicard @davidrose sound off #sxsw http://t.co/k39Hg3Y61b','<a href=\"http://sproutsocial.com\" rel=\"nofollow\">Sprout Social</a>',NULL,NULL,1,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (183,1,'en','3099593356','SXSWrumors','sxswrumor','SXSW','637128264146771968','2015-08-28 06:03:10','Instagram Photos and Videos No Longer Need to Be Square http://t.co/VEgVU6eiRE #SXSW | https://t.co/srBYdgE7Uq http://t.co/0mvg1wFKeB','<a href=\"http://twibble.io\" rel=\"nofollow\">Twibble.io</a>',NULL,NULL,0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (184,1,'en','2980473756','SchooLinks','SchooLinks_News','','637127553090781184','2015-08-28 06:00:20','@ldiamond2 Want to know something cool? We\'re headed to #SXSW, but we need 1 last vote: yours! http://t.co/jYfzPSXUOJ','<a href=\"http://wikihikma.com\" rel=\"nofollow\">Wikihikma</a>','32220475','ldiamond2',0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (185,1,'en','3395767516','SolidRecommendations','SolidRecs','San Francisco, CA','637127099577430016','2015-08-28 05:58:32','Blabbing about blabbing, social selling &amp; #SXSW w/ @jgibbard and myself, waiting on @juliovisko https://t.co/E30CJx2foM #blab','<a href=\"http://www.getnewstweeter.com\" rel=\"nofollow\">TopNewsRetweets</a>',NULL,NULL,1,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (186,1,'en','227517974','JJ Weber','agentjethro','People\'s Republic of Austin','637126933755654144','2015-08-28 05:57:52','So mellow compared to #SXSW but so crazy compared to most cities. #Austin #atx #SixthStreet @ 6th… https://t.co/vRurwZ9xS5','<a href=\"http://instagram.com\" rel=\"nofollow\">Instagram</a>',NULL,NULL,0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (187,1,'en','2980473756','SchooLinks','SchooLinks_News','','637126575033610240','2015-08-28 05:56:27','@Katt_12_21_12 Vote for us, and in return...we\'ll love you : ) #SXSW http://t.co/sWXouzqpxc','<a href=\"http://wikihikma.com\" rel=\"nofollow\">Wikihikma</a>','2382252080','Katt_12_21_12',0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (188,1,'en','2980473756','SchooLinks','SchooLinks_News','','637125501656674304','2015-08-28 05:52:11','@begg_melissa Be a part of the bigger picture today, by voting for into #SXSW  http://t.co/sWXouzqpxc','<a href=\"http://wikihikma.com\" rel=\"nofollow\">Wikihikma</a>','1261315182','begg_melissa',0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (189,1,'en','112986743','Xavier Corman','xaviercorman','Europe','637125314670407680','2015-08-28 05:51:26','Don\'t forget to cast your vote and help send us to #SXSW! http://t.co/yRuPOVOqvL http://t.co/4cxSETfkUh','<a href=\"http://twitter.com/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>',NULL,NULL,2,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (190,1,'en','3105799669','Angie Smith','angiesmith0371','Pleasanton, California','637124680587984896','2015-08-28 05:48:55','Up-vote http://t.co/ZpH0gbZe06 on the #SXSW panel picker if you wanna hear @jaysimons on his path from piano bars to president.','<a href=\"http://twitter.com/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>',NULL,NULL,1,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (191,1,'en','3192600423','Poproxx','poproxx1','Tennessee, USA','637123996060917760','2015-08-28 05:46:12','Dej Loaf Made Her Presence Known at SXSW\n\nhttp://t.co/GtaOREx0Se\n\n#dejloaf #sxsw http://t.co/iY3tIMfAxu','<a href=\"https://www.socialoomph.com\" rel=\"nofollow\">SocialOomph</a>',NULL,NULL,0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (192,1,'en','153998882','Jacqueline','JackieMJensen','','637122827783532544','2015-08-28 05:41:33','RT \"#Startup Hubs Outside the Valley\" http://t.co/XFdgpvdI0f  @jpaine @cherylyeoh @cherylgoh @JackieMJensen #SXSW https://t.co/3eP1735gSv','<a href=\"http://twitter.com\" rel=\"nofollow\">Twitter Web Client</a>',NULL,NULL,1,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (193,1,'en','197108576','Carol Barbee','CBarbee1','','637122724561727489','2015-08-28 05:41:09','Miss #UnREALtv? Feast your eyes on Sequin Raze, the #SXSW 2013 short that inspired the show. http://t.co/vyxLIvHMye http://t.co/T9at4LNiz0','<a href=\"http://twitter.com/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>',NULL,NULL,17,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (194,1,'en','178291443','Moe Saadeh','mysaadeh','Adelaide','637122515031056384','2015-08-28 05:40:19','Black Dog Promotion\'s #SXSW Guide is out! http://t.co/Qloam0dOD3 Stories via @mysaadeh @LeightonSmith12 @CSIdentity','<a href=\"http://twitter.com/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>',NULL,NULL,1,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (195,1,'en','2980473756','SchooLinks','SchooLinks_News','','637120947481350144','2015-08-28 05:34:05','@Ket_Constantine Help our #EdTech Startup get into #SXSW by voting for us : )  http://t.co/i0zv29omxZ','<a href=\"http://wikihikma.com\" rel=\"nofollow\">Wikihikma</a>','1889606419','Ket_Constantine',0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (196,1,'en','2980473756','SchooLinks','SchooLinks_News','','637120093533655040','2015-08-28 05:30:42','@Michael25148804 Make a difference by voting for us into #SXSW #PanelPicker http://t.co/sWXouzqpxc','<a href=\"http://wikihikma.com\" rel=\"nofollow\">Wikihikma</a>','3439377687','Michael25148804',0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (197,1,'en','2980473756','SchooLinks','SchooLinks_News','','637119004738519040','2015-08-28 05:26:22','@Gris912 Quick! Time is running out, vote for us now! #SXSW http://t.co/sWXouzqpxc','<a href=\"http://wikihikma.com\" rel=\"nofollow\">Wikihikma</a>','19289347','Gris912',0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (198,1,'en','243285534','SAVEONMEATS','SAVEONMEATS',' 43 West Hastings Street','637118782368972800','2015-08-28 05:25:29','What #urban #food #security or #innovation questions do you have for us? Ask away! #sxsw @johnandelana @eastvanbrand http://t.co/85Kc9EDtPg','<a href=\"http://www.twitter.com\" rel=\"nofollow\">Twitter for BlackBerry</a>',NULL,NULL,1,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (199,1,'en','2980473756','SchooLinks','SchooLinks_News','','637116733212491776','2015-08-28 05:17:20','@sydneyfishur We\'re the hottest startup in Austin, check us out and vote us into #SXSW http://t.co/sWXouzqpxc','<a href=\"http://wikihikma.com\" rel=\"nofollow\">Wikihikma</a>','479228577','sydneyfishur',0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (200,1,'en','3166615397','Christy Soukhamneut','chrisellaloans','','637116693697961985','2015-08-28 05:17:11','Help get @bryankramer to #SXSW by voting for #Shareology: How Sharing Powers the Human Economy http://t.co/NPI92AXZOe','<a href=\"http://www.influitive.com\" rel=\"nofollow\">Influitive</a>',NULL,NULL,0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (201,1,'en','2980473756','SchooLinks','SchooLinks_News','','637115750625509376','2015-08-28 05:13:26','@bryo2006 Make a difference by voting for us into #SXSW #PanelPicker http://t.co/sWXouzqpxc','<a href=\"http://wikihikma.com\" rel=\"nofollow\">Wikihikma</a>','3340104854','bryo2006',0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (202,1,'en','1636435027','Liz','elizabeth_tx','Texas','637115458240552960','2015-08-28 05:12:16','✅ #SXSW PanelPicker ✅\nhttps://t.co/A5608kaXbR','<a href=\"http://twitter.com\" rel=\"nofollow\">Twitter Web Client</a>',NULL,NULL,3,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (203,1,'en','2680085034','SunPort','PlugSolar','Albuquerque, New Mexico','637115151871664129','2015-08-28 05:11:03','Congratulations @PlugSolar @sunport on the #SharkTank pitch! #atx #austin #texas #SXSW #startup #business #entrepreneur','<a href=\"http://twitter.com/download/android\" rel=\"nofollow\">Twitter for Android</a>',NULL,NULL,2,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (204,1,'en','3003855911','Stacy Markham','AustinpalStacy','','637114977493585920','2015-08-28 05:10:22','_AdrianJackson: Congratulations PlugSolar sunport on the #SharkTank pitch! #atx #austin #texas #SXSW #startup #business #entrepreneur','<a href=\"http://ifttt.com\" rel=\"nofollow\">IFTTT</a>',NULL,NULL,0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (205,1,'en','3221683586','SunPort','sunport','USA','637114961836150788','2015-08-28 05:10:18','Congratulations @PlugSolar @sunport on the #SharkTank pitch! #atx #austin #texas #SXSW #startup #business #entrepreneur','<a href=\"http://twitter.com/download/android\" rel=\"nofollow\">Twitter for Android</a>',NULL,NULL,2,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (206,1,'en','3003855911','Stacy Markham','AustinpalStacy','','637114958766059520','2015-08-28 05:10:17','sunport: RT VanguardBarbers: Congratulations sunport! #atx #austin #texas #SXSW #SharkTank  https://t.co/TmKXItPur1','<a href=\"http://ifttt.com\" rel=\"nofollow\">IFTTT</a>',NULL,NULL,0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (207,1,'en','3003855911','Stacy Markham','AustinpalStacy','','637114957109293057','2015-08-28 05:10:17','VanguardBarbers: Congratulations sunport! #atx #austin #texas #SXSW #SharkTank  https://t.co/TmKXItPur1','<a href=\"http://ifttt.com\" rel=\"nofollow\">IFTTT</a>',NULL,NULL,0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (208,1,'en','2701408981','JILOU mohamed','JILOUmohamed','California, USA','637114803048345600','2015-08-28 05:09:40','Vote for this #SXSW panel to hear 2 #womenintech leaders share their story and give concrete advice http://t.co/iXhzISXrVO','<a href=\"http://twitter.com\" rel=\"nofollow\">Twitter Web Client</a>',NULL,NULL,4,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (209,1,'en','83663729','Adrian Jackson','_AdrianJackson','Austin, Texas','637114452987346944','2015-08-28 05:08:17','Congratulations @PlugSolar @sunport on the #SharkTank pitch! #atx #austin #texas #SXSW #startup #business #entrepreneur','<a href=\"http://twitter.com/download/android\" rel=\"nofollow\">Twitter for Android</a>',NULL,NULL,2,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (210,1,'en','2232601233','John Anderson','tyeeredfish2','','637114428471685120','2015-08-28 05:08:11','Pls RT and vote 4 our #SXSW panel, with @livongo @mysugr @diatribenews @LillyDiabetes http://t.co/hUy7Cjq4Gr','<a href=\"http://twitter.com/#!/download/ipad\" rel=\"nofollow\">Twitter for iPad</a>',NULL,NULL,6,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (211,1,'en','3221683586','SunPort','sunport','USA','637113511907299332','2015-08-28 05:04:32','Congratulations @sunport! #atx #austin #texas #SXSW #SharkTank  https://t.co/1gjNKoR0u6','<a href=\"http://twitter.com/download/android\" rel=\"nofollow\">Twitter for Android</a>',NULL,NULL,1,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (212,1,'en','3186995012','VANGUARD Barber Shop','VanguardBarbers','Austin, TX','637113348731998209','2015-08-28 05:03:53','Congratulations @sunport! #atx #austin #texas #SXSW #SharkTank  https://t.co/1gjNKoR0u6','<a href=\"http://twitter.com/download/android\" rel=\"nofollow\">Twitter for Android</a>',NULL,NULL,1,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (213,1,'en','552094012','Courtney Smith','cshasarrived','San Jose, CA','637113152463892481','2015-08-28 05:03:07','I just voted for @bryankramer #Shareology session in the #SXSW PanelPicker – Show us YOU SHARE and VOTE for it too! https://t.co/6ZclNrbhhL','<a href=\"http://www.tweetjukebox.com\" rel=\"nofollow\">Tweet Jukebox</a>',NULL,NULL,0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (214,1,'en','707359254','Home Movie Legacy','HomeMovieLegacy','Burbank, CA','637112958133346304','2015-08-28 05:02:20','#OndiTimoner 2 times  #SXSW winner does it again with #Brand: A Second Coming','<a href=\"http://www.tweetjukebox.com\" rel=\"nofollow\">Tweet Jukebox</a>',NULL,NULL,0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (215,1,'en','121656574','Jared Polin','froknowsphoto','','637109569588740097','2015-08-28 04:48:52','Word on the street is @froknowsphoto @VideoBlocks may bring Sex, Pixels &amp; Influence to #SXSW...http://t.co/643UuBnW12 http://t.co/uwANdw8U4V','<a href=\"http://twitter.com/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>',NULL,NULL,1,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (216,1,'en','544619544','Mark Brand MB Inc.','eastvanbrand','Love it and it loves back','637108637329063936','2015-08-28 04:45:10','What #urban #food #security or #innovation questions do you have for us? Ask away! #sxsw @johnandelana @eastvanbrand http://t.co/MFF3n2KcRv','<a href=\"http://www.twitter.com\" rel=\"nofollow\">Twitter for BlackBerry</a>',NULL,NULL,1,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (217,1,'en','2980473756','SchooLinks','SchooLinks_News','','637106460640604161','2015-08-28 04:36:31','@elsadelsawelsa Inner City students need our help and we need your help, please vote us into this year\'s #SXSW http://t.co/i0zv29omxZ','<a href=\"http://wikihikma.com\" rel=\"nofollow\">Wikihikma</a>','412830467','elsadelsawelsa',0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (218,1,'en','1211515650','Luke Brown','LukeBrown_AU','Sydney','637106098055565313','2015-08-28 04:35:05','We want to marry #loyalty &amp; #tech. Vote here #SXSW #PanelPicker https://t.co/frXvsxuSkT #marketing RT @AngelaSmithAU http://t.co/aQMWIgpYd1','<a href=\"http://www.hootsuite.com\" rel=\"nofollow\">Hootsuite</a>',NULL,NULL,0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (219,1,'en','3233898667','Yazan Boshmaf','HootYazan','Vancouver, British Columbia','637104333402828800','2015-08-28 04:28:04','Get a behind the scenes look at #SXSW, the most social festival in the world: http://t.co/CgsQekpuzk','<a href=\"http://www.hootsuite.com\" rel=\"nofollow\">Hootsuite</a>',NULL,NULL,0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (220,1,'en','2910393595','Beyond Type 1','BeyondType1','Brooklyn + LA + Silicon Valley','637103598594224129','2015-08-28 04:25:09','Pls RT and vote 4 our #SXSW panel, with @livongo @mysugr @diatribenews @LillyDiabetes http://t.co/hUy7Cjq4Gr','<a href=\"http://twitter.com/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>',NULL,NULL,6,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (221,1,'en','334677429','Autumn A. Arnett','A2Arnett','Greater Washington, DC','637103503215886336','2015-08-28 04:24:46','I didn\'t think I\'d have time to submit @HBCUstory for #SXSW + the good people at Firelight Media did it for me! http://t.co/DvmEbtTnJJ','<a href=\"http://twitter.com\" rel=\"nofollow\">Twitter Web Client</a>',NULL,NULL,1,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (222,1,'en','3192600423','Poproxx','poproxx1','Tennessee, USA','637103445267357696','2015-08-28 04:24:32','SXSW 2015 Recap\n\nhttp://t.co/FQGx1wSCWk\n\n#sxsw #recap #2015 http://t.co/aT0mTRya0T','<a href=\"https://www.socialoomph.com\" rel=\"nofollow\">SocialOomph</a>',NULL,NULL,0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (223,1,'en','2478607224','Sarah Edwards','curlysarah56','Decatur, IL','637103388551987200','2015-08-28 04:24:19','Pls RT and vote 4 our #SXSW panel, with @livongo @mysugr @diatribenews @LillyDiabetes http://t.co/hUy7Cjq4Gr','<a href=\"http://twitter.com/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>',NULL,NULL,6,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (224,1,'en','20771468','Ty Schalter','tyschalter','Lansing, MI','637103166773788672','2015-08-28 04:23:26','Vote for @scATX, @greghoward88, @Travis_Waldron, and my panel at #sxsw on sportswriting and culture! http://t.co/IWv24SJXVs #sxswsports','<a href=\"http://tapbots.com/tweetbot\" rel=\"nofollow\">Tweetbot for iΟS</a>',NULL,NULL,10,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (225,1,'en','185487277','Elton Miranda','eltonmiranda_','San Francisco & Floripa','637103156443369472','2015-08-28 04:23:23','Vote for this #SXSW panel to hear 2 #womenintech leaders share their story and give concrete advice http://t.co/iXhzISXrVO','<a href=\"http://twitter.com/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>',NULL,NULL,4,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (226,1,'en','781163','Kerri / Diabetes','sixuntilme','Rhode Island','637103154308509696','2015-08-28 04:23:23','Pls RT and vote 4 our #SXSW panel, with @livongo @mysugr @diatribenews @LillyDiabetes http://t.co/hUy7Cjq4Gr','<a href=\"https://about.twitter.com/products/tweetdeck\" rel=\"nofollow\">TweetDeck</a>',NULL,NULL,6,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (227,1,'en','1949521','john hanson','pyrotarkus','austin texas usa','637102776674222080','2015-08-28 04:21:53','Join #SXSW in the UK this September at one of our Roadshows! RSVP today: http://t.co/jxfawXBAPM','<a href=\"http://twitter.com/download/android\" rel=\"nofollow\">Twitter for Android</a>',NULL,NULL,8,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (228,1,'en','270587090','Ellen Zehntner','ELZclemson','boston, massachusetts','637102374784487424','2015-08-28 04:20:17','Vote for this #SXSW panel to hear 2 #womenintech leaders share their story and give concrete advice http://t.co/iXhzISXrVO','<a href=\"http://tapbots.com/tweetbot\" rel=\"nofollow\">Tweetbot for iΟS</a>',NULL,NULL,4,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (229,1,'en','1708738633','Simple Job','simple8job','','637102346787549184','2015-08-28 04:20:10','Vote for this #SXSW panel to hear 2 #womenintech leaders share their story and give concrete advice http://t.co/iXhzISXrVO','<a href=\"https://roundteam.co\" rel=\"nofollow\">RoundTeam</a>',NULL,NULL,4,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (230,1,'en','3003855911','Stacy Markham','AustinpalStacy','','637100592947724288','2015-08-28 04:13:12','DogTreatNews: RT #mio_austintexas: http://t.co/G30oIfAp5J .NewLeafActive ~Thx for the follow. I tweet abt #ATX #austin #dogs #sxsw #art #…','<a href=\"http://ifttt.com\" rel=\"nofollow\">IFTTT</a>',NULL,NULL,0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (231,1,'en','3003855911','Stacy Markham','AustinpalStacy','','637100590179463168','2015-08-28 04:13:12','mio_austintexas: .NewLeafActive ~Thx for the follow. I tweet abt #ATX #austin #dogs #sxsw #art #church #education #hiking &amp; more. Keep foll…','<a href=\"http://ifttt.com\" rel=\"nofollow\">IFTTT</a>',NULL,NULL,0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (232,1,'en','2980473756','SchooLinks','SchooLinks_News','','637100322960314368','2015-08-28 04:12:08','@FMichaelCarmody By voting for us, you\'ll help millions of underprivileged students succeed. #SXSW  http://t.co/jYfzPSXUOJ','<a href=\"http://wikihikma.com\" rel=\"nofollow\">Wikihikma</a>','20554438','FMichaelCarmody',0,'no');
insert  into `tweets`(`id`,`campaign_id`,`iso_lang`,`user_id`,`user_name`,`user_screen_name`,`user_location`,`tweet_id`,`created_at`,`content`,`source`,`in_reply_to_id`,`in_reply_to_screen_name`,`retweet_count`,`approved`) values (233,1,'en','13027572','Kissmetrics','Kissmetrics','San Francisco, CA','637100101731786752','2015-08-28 04:11:15','Vote for this #SXSW panel to hear 2 #womenintech leaders share their story and give concrete advice http://t.co/iXhzISXrVO','<a href=\"http://bufferapp.com\" rel=\"nofollow\">Buffer</a>',NULL,NULL,4,'no');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
